# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#04040e\033\\"
printf "\033]4;1;#2b2b35\033\\"
printf "\033]4;2;#3c5564\033\\"
printf "\033]4;3;#797c8b\033\\"
printf "\033]4;4;#7c7e9f\033\\"
printf "\033]4;5;#af9fb5\033\\"
printf "\033]4;6;#a8aed5\033\\"
printf "\033]4;7;#ffffff\033\\"
printf "\033]4;8;#12153c\033\\"
printf "\033]4;9;#353542\033\\"
printf "\033]4;10;#4b697c\033\\"
printf "\033]4;11;#989bae\033\\"
printf "\033]4;12;#9b9cc6\033\\"
printf "\033]4;13;#dac6e2\033\\"
printf "\033]4;14;#d2d9ff\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#04040e\033\\";

# Foreground
printf "\033]10;#ffffff\033\\";

# Cursor
printf "\033]12;#ffffff\033\\";

# Border
printf "\033]7044;#ffffff\033\\";
