# Generated by hellwal

wallpaper='/home/ani/pics/walls/personal/catppuccin/japanese/anime_7.jpeg'

background='04040e'
foreground='ffffff'
cursor='ffffff'
border='ffffff'

color0='04040e'
color1='2b2b35'
color2='3c5564'
color3='797c8b'
color4='7c7e9f'
color5='af9fb5'
color6='a8aed5'
color7='ffffff'
color8='12153c'
color9='353542'
color10='4b697c'
color11='989bae'
color12='9b9cc6'
color13='dac6e2'
color14='d2d9ff'
color15='ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
