# Colorscheme
theme = "catppuccin"

# General settings
[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true

# Cursor shap based on mode
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
